window.PUBLICATIONS = [
  {
    "year": 2026,
    "month": "Jul",
    "title": "Genetic prioritization of HSDL2 in suicide and intentional self-harm: multi-omics evidence linking lipid metabolism and neuronal vulnerability",
    "venue": "BMC Medicine",
    "authors": [
      "Ziyan Zhang",
      "Yutong Wu",
      "Fanxu Meng",
      "Hanbing Ji",
      "Hai Zhong",
      "Shucheng Si",
      "Yun Wei",
      "Yilei Ge",
      "Sijia Wu",
      "Qingxin Luo",
      "Le Wang",
      "Tiemei Liu",
      "Jiawei Xiu",
      "Yiman Guo",
      "Yue Li",
      "Lei Hou",
      "Hao Chen",
      "Xiaoru Sun",
      "Yuanyuan Yu",
      "Qingzhen Hou",
      "Shanshan Gao",
      "Fuzhong Xue",
      "Hongkai Li"
    ],
    "type": "article",
    "cas": "1区 · TOP",
    "peakIF": "11.2",
    "url": "https://doi.org/10.1186/s12916-026-05066-6",
    "doi": "10.1186/s12916-026-05066-6",
    "note": null
  },
  {
    "year": 2026,
    "month": "Jun",
    "title": "Data Resource Profile: Cheeloo Lifespan Electronic-health reseArch Data-library (Cheeloo LEAD)",
    "venue": "International Journal of Epidemiology",
    "authors": [
      "Shuaijie Zhang",
      "Weiwei Chi",
      "Qing Wang",
      "Lei Li",
      "Yongchao Wang",
      "Qi Zhang",
      "Hongkai Li",
      "Xifeng Hu",
      "Qingbo Zhao",
      "Yuanyuan Yu",
      "Xiaoru Sun",
      "Lei Hou",
      "Ping Su",
      "Zhongshang Yuan",
      "Xiaokang Ji",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "2区 · TOP",
    "peakIF": "9.7",
    "url": "https://doi.org/10.1093/ije/dyag091",
    "doi": "10.1093/ije/dyag091",
    "note": null
  },
  {
    "year": 2026,
    "month": "Feb",
    "title": "Transfer learning-based two-sample Mendelian randomization method for heterogeneous population",
    "venue": "Briefings in Bioinformatics",
    "authors": [
      "Yun Wei",
      "Hao Chen",
      "Xinhui Liu",
      "Xiaoru Sun",
      "Yuanyuan Yu",
      "Lei Hou",
      "Fuzhong Xue",
      "Hongkai Li"
    ],
    "type": "article",
    "cas": "2区",
    "peakIF": "14.0",
    "url": "https://doi.org/10.1093/bib/bbag019",
    "doi": "10.1093/bib/bbag019",
    "note": null
  },
  {
    "year": 2026,
    "month": "Jan",
    "title": "Impact of metformin use during pregnancy on fetal congenital malformations across 11 organ systems: a meta-analysis and Drug-Target Mendelian Randomization study",
    "venue": "Diabetes Research and Clinical Practice",
    "authors": [
      "Hanbing Ji",
      "Yutong Wu",
      "Sijia Wu",
      "Xiaoru Sun",
      "Yuanyuan Yu",
      "Lei Hou",
      "Rusong Zhao",
      "Chuan Wang",
      "Yifan Yu",
      "Yilei Ge",
      "Yun Wei",
      "Qingxin Luo",
      "Le Wang",
      "Tiemei Liu",
      "Ziyan Zhang",
      "Jiawei Xiu",
      "Yang Song",
      "Hongkai Li",
      "Shanshan Gao",
      "Fuzhong Xue",
      "Hao Chen"
    ],
    "type": "article",
    "cas": "3区",
    "peakIF": "8.2",
    "url": "https://doi.org/10.1016/j.diabres.2026.113118",
    "doi": "10.1016/j.diabres.2026.113118",
    "note": null
  },
  {
    "year": 2025,
    "month": "Dec",
    "title": "JointMR: A joint likelihood-based approach for causal effect estimation in overlapping Mendelian Randomization studies",
    "venue": "Preprint",
    "authors": [
      "Sijia Wu",
      "Lei Hou",
      "Zhongshang Yuan",
      "Xiaoru Sun",
      "Yuanyuan Yu",
      "Hao Chen",
      "Lin Huang",
      "Fuzhong Xue",
      "Hongkai Li"
    ],
    "type": "preprint",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": "https://doi.org/10.64898/2025.12.18.25342634",
    "doi": "10.64898/2025.12.18.25342634",
    "note": null
  },
  {
    "year": 2025,
    "month": "Dec",
    "title": "Demystifying inconsistent two-sample mendelian randomization estimations using selection diagram",
    "venue": "BMC Medical Research Methodology",
    "authors": [
      "Lei Hou",
      "Yuanyuan Yu",
      "Zhi Geng",
      "Fuzhong Xue",
      "Hongkai Li"
    ],
    "type": "article",
    "cas": "3区",
    "peakIF": "4.6",
    "url": "https://doi.org/10.1186/s12874-025-02707-x",
    "doi": "10.1186/s12874-025-02707-x",
    "note": null
  },
  {
    "year": 2025,
    "month": "Aug",
    "title": "MR-EILLS: an invariance-based Mendelian randomization method integrating multiple heterogeneous GWAS summary datasets",
    "venue": "Nature Communications",
    "authors": [
      "Lei Hou",
      "Hao Chen",
      "Xiao-Hua Zhou"
    ],
    "type": "article",
    "cas": "1区 · TOP",
    "peakIF": "18.1",
    "url": "https://doi.org/10.1038/s41467-025-62823-6",
    "doi": "10.1038/s41467-025-62823-6",
    "note": null
  },
  {
    "year": 2025,
    "month": "May",
    "title": "Impact of Metformin Use During Pregnancy on Fetal Congenital Malformations Across 11 Organ Systems: A Sex-Specific Analysis",
    "venue": "Preprint",
    "authors": [
      "Hanbing Ji",
      "Yutong Wu",
      "Sijia Wu",
      "Xiaoru Sun",
      "Yuanyuan Yu",
      "Lei Hou",
      "Chuan Wang",
      "Yifan Yu",
      "Yilei Ge",
      "Yun Wei",
      "Qingxin Luo",
      "Le Wang",
      "Tiemei Liu",
      "Ziyan Zhang",
      "Jiawei Xiu",
      "Hongkai Li",
      "Fan Jiang",
      "Fuzhong Xue",
      "Hao Chen"
    ],
    "type": "preprint",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": "https://doi.org/10.2139/ssrn.5216161",
    "doi": "10.2139/ssrn.5216161",
    "note": null
  },
  {
    "year": 2025,
    "month": "Jan",
    "title": "TEMR: Trans-ethnic mendelian randomization method using large-scale GWAS summary datasets",
    "venue": "The American Journal of Human Genetics",
    "authors": [
      "Lei Hou",
      "Sijia Wu",
      "Zhongshang Yuan",
      "Fuzhong Xue",
      "Hongkai Li"
    ],
    "type": "article",
    "cas": "1区 · TOP",
    "peakIF": "11.0",
    "url": "https://doi.org/10.1016/j.ajhg.2024.11.006",
    "doi": "10.1016/j.ajhg.2024.11.006",
    "note": "Online 2024"
  },
  {
    "year": 2024,
    "month": "Aug",
    "title": "A novel constraint-based structure learning algorithm using marginal causal prior knowledge",
    "venue": "Scientific Reports",
    "authors": [
      "Yifan Yu",
      "Lei Hou",
      "Xinhui Liu",
      "Sijia Wu",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "3区",
    "peakIF": "5.0",
    "url": "https://doi.org/10.1038/s41598-024-68379-7",
    "doi": "10.1038/s41598-024-68379-7",
    "note": null
  },
  {
    "year": 2024,
    "month": "Jun",
    "title": "TEMR: Trans-ethnic Mendelian Randomization Method using Large-scale GWAS Summary Datasets",
    "venue": "Preprint",
    "authors": [
      "Lei Hou",
      "Sijia Wu",
      "Zhongshang Yuan",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "preprint",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": "https://doi.org/10.1101/2024.06.16.24308874",
    "doi": "10.1101/2024.06.16.24308874",
    "note": null
  },
  {
    "year": 2024,
    "month": "Mar",
    "title": "MRSL: a causal network pruning algorithm based on GWAS summary data",
    "venue": "Briefings in Bioinformatics",
    "authors": [
      "Lei Hou",
      "Zhi Geng",
      "Zhongshang Yuan",
      "Xu Shi",
      "Chuan Wang",
      "Feng Chen",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "2区",
    "peakIF": "14.0",
    "url": "https://doi.org/10.1093/bib/bbae086",
    "doi": "10.1093/bib/bbae086",
    "note": null
  },
  {
    "year": 2024,
    "month": "Jan",
    "title": "The Long-term Mediation Role of Cytokines on the Causal Pathway from Maternal Gestational Age to Offspring Eye Diseases: Lifecourse-Network Mendelian Randomization",
    "venue": "Preprint",
    "authors": [
      "Lei Hou",
      "Yunxia Li",
      "Lili Kang",
      "Xiaoying Li",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "preprint",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": "https://doi.org/10.22541/au.170663642.25288666/v1",
    "doi": "10.22541/au.170663642.25288666/v1",
    "note": null
  },
  {
    "year": 2023,
    "month": "Oct",
    "title": "Causal associations between female reproductive behaviors and psychiatric disorders: a lifecourse Mendelian randomization study",
    "venue": "BMC Psychiatry",
    "authors": [
      "Yifan Yu",
      "Lei Hou",
      "Yutong Wu",
      "Yuanyuan Yu",
      "Xinhui Liu",
      "Sijia Wu",
      "Yina He",
      "Yilei Ge",
      "Yun Wei",
      "Fengtong Qian",
      "Qingxin Luo",
      "Yue Feng",
      "Xiaojing Cheng",
      "Tiangui Yu",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "3区",
    "peakIF": "4.6",
    "url": "https://doi.org/10.1186/s12888-023-05203-y",
    "doi": "10.1186/s12888-023-05203-y",
    "note": null
  },
  {
    "year": 2023,
    "month": "Jun",
    "title": "The long-term mediation role of cytokines on the causal pathway from maternal gestational age to offspring eye diseases: Lifecourse-Network Mendelian randomization",
    "venue": "International Immunopharmacology",
    "authors": [
      "Lei Hou",
      "Yunxia Li",
      "Lili Kang",
      "Xiaoying Li",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "2区",
    "peakIF": "5.7",
    "url": null,
    "doi": null,
    "note": null
  },
  {
    "year": 2023,
    "month": "Jun",
    "title": "Association between dietary habits and the risk of migraine: a Mendelian randomization study",
    "venue": "Frontiers in Nutrition",
    "authors": [
      "Xinhui Liu",
      "Yuanyuan Yu",
      "Lei Hou",
      "Yifan Yu",
      "Yutong Wu",
      "Sijia Wu",
      "Yina He",
      "Yilei Ge",
      "Yun Wei",
      "Qingxin Luo",
      "Fengtong Qian",
      "Yue Feng",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "2区",
    "peakIF": "6.6",
    "url": "https://doi.org/10.3389/fnut.2023.1123657",
    "doi": "10.3389/fnut.2023.1123657",
    "note": null
  },
  {
    "year": 2023,
    "month": "Mar",
    "title": "Causal associations between female reproductive behaviors and psychiatric disorders: a lifecourse Mendelian randomization study",
    "venue": "Preprint",
    "authors": [
      "Yifan Yu",
      "Lei Hou",
      "Yutong Wu",
      "Yuanyuan Yu",
      "Xinhui Liu",
      "Sijia Wu",
      "Yina He",
      "Yilei Ge",
      "Yun Wei",
      "Fengtong Qian",
      "Qingxin Luo",
      "Yue Feng",
      "Xiaojing Cheng",
      "Tiangui Yu",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "preprint",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": "https://doi.org/10.1101/2023.03.20.23287480",
    "doi": "10.1101/2023.03.20.23287480",
    "note": null
  },
  {
    "year": 2023,
    "month": "Jan",
    "title": "Lipid-Lowering Drug Targets and Risk of Non-Alcoholic Fatty Liver Disease: Mendelian Randomization and Colocalization Analyses",
    "venue": "Preprint",
    "authors": [
      "Qian Fengtong",
      "Yuanyuan Yu",
      "Lei Hou",
      "Xinhui Liu",
      "Yifan Yu",
      "Yutong Wu",
      "Sijia Wu",
      "Yina He",
      "Yilei Ge",
      "Yun Wei",
      "Qingxin Luo",
      "Yue Feng",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "preprint",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": "https://doi.org/10.2139/ssrn.4366878",
    "doi": "10.2139/ssrn.4366878",
    "note": null
  },
  {
    "year": 2022,
    "month": "Nov",
    "title": "Quantifying substantial carcinogenesis of genetic and environmental factors from measurement error in the number of stem cell divisions",
    "venue": "BMC Cancer",
    "authors": [
      "Xinhui Liu",
      "Jifeng Yang",
      "Hongkai Li",
      "Qing Wang",
      "Yuanyuan Yu",
      "Xiaoru Sun",
      "Shucheng Si",
      "Lei Hou",
      "Lu Liu",
      "Fan Yang",
      "Ran Yan",
      "Yifan Yu",
      "Zhentao Fu",
      "Zilong Lu",
      "Dejin Li",
      "Hao Xue",
      "Xiaolei Guo",
      "Fuzhong Xue",
      "Xiaokang Ji"
    ],
    "type": "article",
    "cas": "3区",
    "peakIF": "4.6",
    "url": "https://doi.org/10.1186/s12885-022-10219-w",
    "doi": "10.1186/s12885-022-10219-w",
    "note": null
  },
  {
    "year": 2022,
    "month": "Oct",
    "title": "Identification of Causal Pathways among Gut Microbiota, Food Intake and Telomere Length: A Mendelian Randomization Study",
    "venue": "Preprint",
    "authors": [
      "Lei Hou",
      "Yuanyuan Yu",
      "Chuandi Jin",
      "Lei Zhang",
      "Yilei Ge",
      "Xinhui Liu",
      "Sijia Wu",
      "Fengtong Qian",
      "Yutong Wu",
      "Yifan Yu",
      "Qingxin Luo",
      "Yina He",
      "Yue Feng",
      "Yun Wei",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "preprint",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": "https://doi.org/10.21203/rs.3.rs-2141157/v1",
    "doi": "10.21203/rs.3.rs-2141157/v1",
    "note": null
  },
  {
    "year": 2022,
    "month": "Sep",
    "title": "Identification of Causal Pathways among Gut Microbiota, Food Intake and Telomere Length: A Mendelian Randomization Study",
    "venue": "Preprint",
    "authors": [
      "Lei Hou",
      "Yuanyuan Yu",
      "Chuandi Jin",
      "Lei Zhang",
      "Yilei Ge",
      "Xinhui Liu",
      "Sijia Wu",
      "Fengtong Qian",
      "Yutong Wu",
      "Yifan Yu",
      "Qingxin Luo",
      "Yina He",
      "Yue Feng",
      "Yun Wei",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "preprint",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": "https://doi.org/10.1101/2022.09.22.22280255",
    "doi": "10.1101/2022.09.22.22280255",
    "note": null
  },
  {
    "year": 2022,
    "month": "Aug",
    "title": "Comparative efficacy and safety of glucose-lowering drugs in children and adolescents with type 2 diabetes: A systematic review and network meta-analysis",
    "venue": "Frontiers in Endocrinology",
    "authors": [
      "Sijia Wu",
      "Yina He",
      "Yutong Wu",
      "Yiman Ji",
      "Lei Hou",
      "Xinhui Liu",
      "Yilei Ge",
      "Yuanyuan Yu",
      "Yifan Yu",
      "Yun Wei",
      "Fengtong Qian",
      "Qingxin Luo",
      "Yue Feng",
      "Yiping Feng",
      "Jiongjiong Wang",
      "Meiling Huo",
      "Hongkai Li",
      "Fuzhong Xue",
      "Yunxia Liu"
    ],
    "type": "article",
    "cas": "3区",
    "peakIF": "6.1",
    "url": "https://doi.org/10.3389/fendo.2022.897776",
    "doi": "10.3389/fendo.2022.897776",
    "note": null
  },
  {
    "year": 2022,
    "month": "Jun",
    "title": "MRSL: A phenome-wide causal discovery algorithm based on GWAS summary data",
    "venue": "Preprint",
    "authors": [
      "Lei Hou",
      "Zhi Geng",
      "Xu Shi",
      "Chuan Wang",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "preprint",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": null,
    "doi": null,
    "note": null
  },
  {
    "year": 2022,
    "month": "May",
    "title": "Exploring the Causal Roles of Circulating Remnant Lipid Profile on Cardiovascular and Cerebrovascular Diseases: Mendelian Randomization Study",
    "venue": "Journal of Epidemiology",
    "authors": [
      "Shucheng Si",
      "Lei Hou",
      "Xiaolu Chen",
      "Wenchao Li",
      "Xinhui Liu",
      "Congcong Liu",
      "Yunxia Li",
      "Tonghui Yuan",
      "Jiqing Li",
      "Bojie Wang",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "3区",
    "peakIF": "4.7",
    "url": "https://doi.org/10.2188/jea.JE20200305",
    "doi": "10.2188/jea.JE20200305",
    "note": null
  },
  {
    "year": 2022,
    "month": "Mar",
    "title": "Causal mediation analysis with multiple causally non-ordered and ordered mediators based on summarized genetic data",
    "venue": "Statistical Methods in Medical Research",
    "authors": [
      "Lei Hou",
      "Yuanyuan Yu",
      "Xiaoru Sun",
      "Xinhui Liu",
      "Yifan Yu",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "3区",
    "peakIF": "3.0",
    "url": "https://doi.org/10.1177/09622802221084599",
    "doi": "10.1177/09622802221084599",
    "note": null
  },
  {
    "year": 2022,
    "month": "Mar",
    "title": "Impact of nonrandom selection mechanisms on the causal effect estimation for two-sample Mendelian randomization methods",
    "venue": "PLOS Genetics",
    "authors": [
      "Yuanyuan Yu",
      "Lei Hou",
      "Xu Shi",
      "Xiaoru Sun",
      "Xinhui Liu",
      "Yifan Yu",
      "Zhongshang Yuan",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "2区 · TOP",
    "peakIF": "6.0",
    "url": "https://doi.org/10.1371/journal.pgen.1010107",
    "doi": "10.1371/journal.pgen.1010107",
    "note": null
  },
  {
    "year": 2021,
    "month": "Dec",
    "title": "Adjustment for SNPs instead of demographic and clinical covariates in GWAS",
    "venue": "Preprint",
    "authors": [
      "Fuzhong Xue",
      "Xiaoru Sun",
      "Hongkai Li",
      "Yuanyuan Yu",
      "Zhongshang Yuan",
      "Chuandi Jin",
      "Lei Hou",
      "Xinhui Liu",
      "Qing Wang"
    ],
    "type": "preprint",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": "https://doi.org/10.1101/2021.12.22.473912",
    "doi": "10.1101/2021.12.22.473912",
    "note": null
  },
  {
    "year": 2021,
    "month": "Dec",
    "title": "Consequence of adjustments for demographic or clinical covariates and a recommended solution in genome-wide association studies",
    "venue": "Preprint",
    "authors": [
      "Xiaoru Sun",
      "Hongkai Li",
      "Yuanyuan Yu",
      "Zhongshang Yuan",
      "Chuandi Jin",
      "Lei Hou",
      "Xinhui Liu",
      "Qing Wang",
      "Fuzhong Xue"
    ],
    "type": "preprint",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": "https://doi.org/10.1101/2021.12.07.471675",
    "doi": "10.1101/2021.12.07.471675",
    "note": null
  },
  {
    "year": 2021,
    "month": "Aug",
    "title": "Genetically Predicted Insomnia in Relation to 14 Cardiovascular Conditions and 17 Cardiometabolic Risk Factors: A Mendelian Randomization Study",
    "venue": "Journal of the American Heart Association",
    "authors": [
      "Xinhui Liu",
      "Chuanbao Li",
      "Xiaoru Sun",
      "Yuanyuan Yu",
      "Shucheng Si",
      "Lei Hou",
      "Ran Yan",
      "Yifan Yu",
      "Mingzhuo Li",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "1区 · TOP",
    "peakIF": "6.1",
    "url": "https://doi.org/10.1161/JAHA.120.020187",
    "doi": "10.1161/JAHA.120.020187",
    "note": null
  },
  {
    "year": 2021,
    "month": "Jul",
    "title": "A Negative Control Outcome Regression Accounting for Unobserved Confounding and Lagged Causal Effects",
    "venue": "Preprint",
    "authors": [
      "Hongkai Li",
      "Yuanyuan Yu",
      "Lei Hou",
      "Xiaoru Sun",
      "Xinhui Liu",
      "Fan Yang",
      "Yifan Yu",
      "Qing Wang",
      "Fuzhong Xue"
    ],
    "type": "preprint",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": "https://doi.org/10.21203/rs.3.rs-696980/v1",
    "doi": "10.21203/rs.3.rs-696980/v1",
    "note": null
  },
  {
    "year": 2021,
    "month": "May",
    "title": "Identification of microenvironment related potential biomarkers of biochemical recurrence at 3 years after prostatectomy in prostate adenocarcinoma",
    "venue": "Aging",
    "authors": [
      "Xiaoru Sun",
      "Lu Wang",
      "Hongkai Li",
      "Chuandi Jin",
      "Yuanyuan Yu",
      "Lei Hou",
      "Xinhui Liu",
      "Yifan Yu",
      "Ran Yan",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "3区（2024版）",
    "peakIF": "6.0",
    "url": "https://doi.org/10.18632/aging.203121",
    "doi": "10.18632/aging.203121",
    "note": null
  },
  {
    "year": 2021,
    "month": "Jun",
    "title": "Causal effect of sex hormone-binding globulin and testosterone on coronary heart disease: A multivariable and network Mendelian randomization analysis",
    "venue": "International Journal of Cardiology",
    "authors": [
      "Yunxia Li",
      "Shucheng Si",
      "Lei Hou",
      "Tonghui Yuan",
      "Xiaolu Chen",
      "Congcong Liu",
      "Wenchao Li",
      "Hongkai Li",
      "Yanxun Liu",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "2区",
    "peakIF": "4.2",
    "url": "https://doi.org/10.1016/j.ijcard.2021.06.037",
    "doi": "10.1016/j.ijcard.2021.06.037",
    "note": null
  },
  {
    "year": 2021,
    "month": "Apr",
    "title": "Lipids, Anthropometric Measures, Smoking and Physical Activity Mediate the Causal Pathway from Education to Breast Cancer in Women: A Mendelian Randomization Study",
    "venue": "Preprint",
    "authors": [
      "Hongkai Li",
      "Lei Hou",
      "Yuanyuan Yu",
      "Xiaoru Sun",
      "Xinhui Liu",
      "Yifan Yu",
      "Sijia Wu",
      "Yina He",
      "Yutong Wu",
      "Li He",
      "Fuzhong Xue"
    ],
    "type": "preprint",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": null,
    "doi": null,
    "note": null
  },
  {
    "year": 2021,
    "month": "Mar",
    "title": "Exploring the causal pathway from bilirubin to CVD and diabetes in the UK Biobank Cohort Study: Observational findings and Mendelian randomization studies",
    "venue": "Atherosclerosis",
    "authors": [
      "Lei Hou",
      "Hongkai Li",
      "Shucheng Si",
      "Yuanyuan Yu",
      "Xiaoru Sun",
      "Xinhui Liu",
      "Ran Yan",
      "Yifan Yu",
      "Chuan Wang",
      "Fan Yang",
      "Qing Wang",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "2区 · TOP",
    "peakIF": "6.8",
    "url": "https://doi.org/10.1016/j.atherosclerosis.2020.12.005",
    "doi": "10.1016/j.atherosclerosis.2020.12.005",
    "note": null
  },
  {
    "year": 2021,
    "month": "Jan",
    "title": "Causal Effect of the Triglyceride-Glucose Index and the Joint Exposure of Higher Glucose and Triglyceride With Extensive Cardio-Cerebrovascular Metabolic Outcomes in the UK Biobank: A Mendelian Randomization Study",
    "venue": "Frontiers in Cardiovascular Medicine",
    "authors": [
      "Shucheng Si",
      "Jiqing Li",
      "Yunxia Li",
      "Wenchao Li",
      "Xiaolu Chen",
      "Tonghui Yuan",
      "Congcong Liu",
      "Hongkai Li",
      "Lei Hou",
      "Bojie Wang",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "3区",
    "peakIF": "6.1",
    "url": "https://doi.org/10.3389/fcvm.2020.583473",
    "doi": "10.3389/fcvm.2020.583473",
    "note": null
  },
  {
    "year": 2021,
    "month": "Jan",
    "title": "Causal Mediation Analysis with Multiple Causally Ordered and Non-ordered Mediators based on Summarized Genetic Data",
    "venue": "Preprint",
    "authors": [
      "Lei Hou",
      "Yuanyuan Yu",
      "Xiaoru Sun",
      "Xinhui Liu",
      "Yifan Yu",
      "Ran Yan",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "preprint",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": "https://doi.org/10.1101/2021.01.07.21249415",
    "doi": "10.1101/2021.01.07.21249415",
    "note": null
  },
  {
    "year": 2021,
    "month": "Dec",
    "title": "Lipids, Anthropometric Measures, Smoking and Physical Activity Mediate the Causal Pathway From Education to Breast Cancer in Women: A Mendelian Randomization Study",
    "venue": "Journal of Breast Cancer",
    "authors": [
      "Hongkai Li",
      "Lei Hou",
      "Yuanyuan Yu",
      "Xiaoru Sun",
      "Xinhui Liu",
      "Yifan Yu",
      "Sijia Wu",
      "Yina He",
      "Yutong Wu",
      "Li He",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "4区",
    "peakIF": "3.6",
    "url": "https://doi.org/10.4048/jbc.2021.24.e53",
    "doi": "10.4048/jbc.2021.24.e53",
    "note": null
  },
  {
    "year": 2020,
    "month": "Dec",
    "title": "Exploring the Causal Pathway from Bilirubin to CVD and Diabetes in the UK Biobank Cohort Study: Observational findings and Mendelian randomization studies",
    "venue": "Atherosclerosis",
    "authors": [
      "Lei Hou",
      "Hongkai Li",
      "Yuanyuan Yu",
      "Xiaoru Sun",
      "Xinhui Liu",
      "Ran Yan",
      "Yifan Yu",
      "Chuan Wang",
      "Fan Yang",
      "Qing Wang",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "2区 · TOP",
    "peakIF": "6.8",
    "url": "https://doi.org/10.1016/j.atherosclerosis.2020.12.005",
    "doi": "10.1016/j.atherosclerosis.2020.12.005",
    "note": "Online-first record"
  },
  {
    "year": 2020,
    "month": "Aug",
    "title": "Identification and Estimation of Causal Effects Using a Negative-Control Exposure in Time-Series Studies With Applications to Environmental Epidemiology",
    "venue": "American Journal of Epidemiology",
    "authors": [
      "Yuanyuan Yu",
      "Hongkai Li",
      "Xiaoru Sun",
      "Xinhui Liu",
      "Fan Yang",
      "Lei Hou",
      "Lu Liu",
      "Ran Yan",
      "Yifan Yu",
      "Ming Jing",
      "Hao Xue",
      "Wuchun Cao",
      "Qing Wang",
      "Hua Zhong",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "2区",
    "peakIF": "5.4",
    "url": "https://doi.org/10.1093/aje/kwaa172",
    "doi": "10.1093/aje/kwaa172",
    "note": null
  },
  {
    "year": 2020,
    "month": "Jun",
    "title": "A novel method for controlling unobserved confounding using double confounders",
    "venue": "BMC Medical Research Methodology",
    "authors": [
      "Lu Liu",
      "Lei Hou",
      "Yuanyuan Yu",
      "Xinhui Liu",
      "Xiaoru Sun",
      "Fan Yang",
      "Qing Wang",
      "Ming Jing",
      "Yeping Xu",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "3区",
    "peakIF": "4.6",
    "url": "https://doi.org/10.1186/s12874-020-01049-0",
    "doi": "10.1186/s12874-020-01049-0",
    "note": null
  },
  {
    "year": 2020,
    "month": "May",
    "title": "Causal Pathways from Body Components and Regional Fat to Extensive Metabolic Phenotypes: A Mendelian Randomization Study",
    "venue": "Obesity",
    "authors": [
      "Shucheng Si",
      "Marlvin Anemey Tewara",
      "Yunxia Li",
      "Wenchao Li",
      "Xiaolu Chen",
      "Tonghui Yuan",
      "Congcong Liu",
      "Jiqing Li",
      "Bojie Wang",
      "Hongkai Li",
      "Lei Hou",
      "Qing Wang",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "2区",
    "peakIF": "9.3",
    "url": "https://doi.org/10.1002/oby.22857",
    "doi": "10.1002/oby.22857",
    "note": null
  },
  {
    "year": 2020,
    "month": "Jul",
    "title": "Roles for circulating polyunsaturated fatty acids in ischemic stroke and modifiable factors: A Mendelian randomization study",
    "venue": "Nutrition Journal",
    "authors": [
      "Tonghui Yuan",
      "Shucheng Si",
      "Yunxia Li",
      "Wenchao Li",
      "Xiaolu Chen",
      "Congcong Liu",
      "Jiqing Li",
      "Bojie Wang",
      "Lei Hou",
      "Yanxun Liu",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "2区",
    "peakIF": "5.4",
    "url": "https://doi.org/10.1186/s12937-020-00582-4",
    "doi": "10.1186/s12937-020-00582-4",
    "note": null
  },
  {
    "year": 2020,
    "month": "May",
    "title": "Evaluating the causal relationship between hip circumference and coronary heart disease: a Mendelian randomization study",
    "venue": "Journal of Hygiene Research",
    "authors": [
      "Tonghui Yuan",
      "Hongkai Li",
      "Yuntao Ma",
      "Shucheng Si",
      "Xinhui Liu",
      "Yuanyuan Yu",
      "Yunxia Li",
      "Wenchao Li",
      "Lei Hou",
      "Lu Liu",
      "Yuchang Zhou",
      "Fuzhong Xue",
      "Ping Wang",
      "Yanxun Liu"
    ],
    "type": "article",
    "cas": "N/A",
    "peakIF": "N/A",
    "url": "https://doi.org/10.19813/j.cnki.weishengyanjiu.2020.03.003",
    "doi": "10.19813/j.cnki.weishengyanjiu.2020.03.003",
    "note": null
  },
  {
    "year": 2020,
    "month": "Jan",
    "title": "Exploring the causal pathway from ischemic stroke to atrial fibrillation: a network Mendelian randomization study",
    "venue": "Molecular Medicine",
    "authors": [
      "Lei Hou",
      "Mingqing Xu",
      "Yuanyuan Yu",
      "Xiaoru Sun",
      "Xinhui Liu",
      "Lu Liu",
      "Yunxia Li",
      "Tonghui Yuan",
      "Wenchao Li",
      "Hongkai Li",
      "Fuzhong Xue"
    ],
    "type": "article",
    "cas": "2区",
    "peakIF": "6.4",
    "url": "https://doi.org/10.1186/s10020-019-0133-y",
    "doi": "10.1186/s10020-019-0133-y",
    "note": null
  }
];
