(() => {
const T={
zh:{
 navAbout:"关于",navResearch:"研究",navProjects:"项目",navWorks:"论文",navJourney:"经历",navTeaching:"教学",allPubsShort:"ALL PAPERS ↗",
 heroRole:"山东大学公共卫生学院 · 副研究员",heroStatement:"以可迁移、可识别、可验证的统计方法，重建复杂生物医学数据中的因果结构。",exploreResearch:"VIEW RESEARCH ↓",
 statOutputs:"研究成果",statLeadCount:"近20篇",statLead:"第一 / 通讯作者论文",statProjects:"主持科研项目",statPillars:"核心研究方向",
 aboutTitle:"用方法理解复杂医学问题",aboutBody:"我主要从事大数据时代下生物统计、遗传统计与因果推断的创新统计方法及其应用研究。核心兴趣不是为单一数据集寻找一个“最好看的答案”，而是在跨人群、跨环境、多源数据和真实世界偏倚存在时，建立仍然可识别、可迁移、可解释的因果证据。",positionText:"副研究员 · 山东大学公共卫生学院",
 researchTitle:"构建可信的因果学习",
 r1Title:"跨人群与多源数据因果学习",r1Body:"研究人群异质、样本不平衡与多中心数据条件下的迁移学习、跨祖源MR与联邦因果推断，让证据能够跨场景迁移而不牺牲识别可靠性。",
 r2Title:"因果结构与机制发现",r2Body:"从单一因果效应走向结构：发展高维因果图、网络裁剪、多中介与路径识别方法，回答复杂疾病中“谁影响谁、通过什么机制”的问题。",
 r3Title:"偏倚与混杂下的稳健识别",r3Body:"围绕未知混杂、选择偏倚、多效性和分布漂移，研究工具变量、不变性与稳健估计，使因果结论对现实数据的不完美更有抵抗力。",
 r4Title:"统计遗传与转化健康",r4Body:"将方法落到多组学靶点发现、复杂疾病机制、本土队列与精准防控场景中，把统计创新连接到可验证、可复现和可转化的医学问题。",
 projectsTitle:"主持科研项目",p1Agency:"国家自然科学基金",p1Title:"融合生物先验与迁移学习的高维病因网络构建方法研究",p2Agency:"山东省自然科学基金",p2Title:"联邦迁移学习框架下的非线性因果推断方法研究",p3Agency:"中国博士后科学基金",p3Title:"第17批特别资助",p4Title:"第75批面上资助",p5Agency:"国家资助博士后研究人员计划",p5Title:"B档资助（博新计划进入会评）",p6Agency:"北京大学",p6Title:"博雅博士后计划",
 worksTitle:"代表性论文",allPubs:"查看全部论文、作者、分区与IF",
 journeyTitle:"从统计学走向因果方法",j4Title:"山东大学 · 公共卫生学院",j4Body:"副研究员 / Associate Research Fellow",j3Title:"北京大学 · 北京国际数学研究中心",j3Body:"博士后 / 助理研究员",j2Title:"山东大学 · 公共卫生学院",j2Body:"流行病与卫生统计学 · 博士",j1Title:"山东大学 · 数学与统计学院",j1Body:"统计学 · 学士",
 teachingTitle:"教学与教材建设",teachA:"教学",ugLabel:"本科生课程",gradLabel:"研究生课程",courseUG1:"《大数据流行病学技术》",courseUG1Meta:"16 学时 · 选修课",courseUG2:"《健康大数据编程基础》",courseUG2Meta:"16 学时 · 必修课",courseUG4:"《流行病与卫生统计》",courseUG4Meta:"48 学时 · 必修课",courseG1:"《生物统计中的数学基础》",courseG1Meta:"24 学时",teachingAwardsLabel:"教学成果与教材",teachBook1:"《大数据流行病学》副主编",teachBook2:"《统计学》副主编",teachAward1:"山东大学青年教师教学比赛二等奖",teachAward2:"山东大学公共卫生学院青年教师教学比赛二等奖",serviceTitle:"社会与学术兼职",serviceA:"社会兼职",service1:"中国现场统计学会因果推断分会理事",service2:"山东预防医学会消化病与健康分会委员",service3:"EngMedicine 医工交叉期刊青年编委",patentTitle:"专利与成果转化",patentA:"专利转化",patent1:"授权发明专利 1 项",patent2:"“一种基于因果网络不确定性推理的疾病预测预警系统”",patent3:"已完成科技成果转化",patentStatus:"已授权 · 已转化",
 footerQuote:"Build methods that survive heterogeneity.",
 pubTitle:"论文与研究成果",pubLead:"期刊论文同时显示中科院分区与近5年最高JIF。",metricNote:"指标口径：中科院分区采用2025升级版公开信息；“5Y Max IF”为2021–2025期间公开JCR记录中的最高JIF，四舍五入到1位小数。预印本及非JCR期刊标记为N/A。期刊指标会年度变化，正式申报前建议再次核验。",
 searchLabel:"检索",searchPlaceholder:"题目 / 作者 / 期刊",filterAll:"全部",filterArticles:"期刊论文",filterPreprints:"预印本",allYears:"全部年份",resultsLabel:"项成果",noResults:"没有匹配结果。",articleLabel:"期刊论文",preprintLabel:"预印本",casLabel:"中科院",ifLabel:"5Y MAX IF"
},
en:{
 navAbout:"About",navResearch:"Research",navProjects:"Projects",navWorks:"Papers",navJourney:"Journey",navTeaching:"Teaching",allPubsShort:"ALL PAPERS ↗",
 heroRole:"Associate Research Fellow · School of Public Health, Shandong University",heroStatement:"Building transferable, identifiable and verifiable causal methods for complex biomedical data.",exploreResearch:"VIEW RESEARCH ↓",
 statOutputs:"RESEARCH OUTPUTS",statLeadCount:"~20",statLead:"FIRST / CORRESPONDING",statProjects:"PI PROJECTS",statPillars:"RESEARCH PILLARS",
 aboutTitle:"Methods for Complex Medical Questions",aboutBody:"My work sits at the intersection of biostatistics, statistical genetics and causal inference. Rather than optimizing an answer for a single dataset, I focus on causal evidence that remains identifiable, transferable and interpretable across populations, environments, heterogeneous data sources and real-world bias.",positionText:"Associate Research Fellow · School of Public Health, Shandong University",
 researchTitle:"Credible Causal Learning",
 r1Title:"Causal Learning Across Populations & Data Sources",r1Body:"Transfer learning, trans-ancestry Mendelian randomization and federated causal inference under population heterogeneity, sample imbalance and multi-site data.",
 r2Title:"Causal Structure & Mechanism Discovery",r2Body:"High-dimensional causal graphs, network pruning, mediation and pathway identification for moving from single effects to mechanistic structure.",
 r3Title:"Robust Identification Under Bias & Confounding",r3Body:"Instrumental variables, causal invariance and robust estimation under unmeasured confounding, selection bias, pleiotropy and distribution shift.",
 r4Title:"Statistical Genetics for Translational Health",r4Body:"Connecting statistical methods with multi-omics target discovery, disease mechanisms, real-world cohorts and precision prevention.",
 projectsTitle:"PI Research Projects",p1Agency:"National Natural Science Foundation of China",p1Title:"High-dimensional etiological network construction integrating biological priors and transfer learning",p2Agency:"Natural Science Foundation of Shandong Province",p2Title:"Nonlinear causal inference under a federated transfer-learning framework",p3Agency:"China Postdoctoral Science Foundation",p3Title:"17th Special Funding",p4Title:"75th General Program",p5Agency:"National-funded Postdoctoral Researcher Program",p5Title:"Category B",p6Agency:"Peking University",p6Title:"Boya Postdoctoral Program",
 worksTitle:"Selected Publications",allPubs:"VIEW ALL PAPERS, AUTHORS & METRICS",
 journeyTitle:"From Statistics to Causal Methods",j4Title:"Shandong University · School of Public Health",j4Body:"Associate Research Fellow",j3Title:"Peking University · Beijing International Center for Mathematical Research",j3Body:"Postdoctoral Fellow / Assistant Research Fellow",j2Title:"Shandong University",j2Body:"Ph.D. in Epidemiology and Health Statistics",j1Title:"Shandong University",j1Body:"B.Sc. in Statistics",
 teachingTitle:"Teaching & Textbooks",teachA:"Teaching",ugLabel:"Undergraduate Courses",gradLabel:"Graduate Course",courseUG1:"Big Data Epidemiology Technology",courseUG1Meta:"16 hours · Elective",courseUG2:"Programming Fundamentals for Health Big Data",courseUG2Meta:"16 hours · Required",courseUG4:"Epidemiology and Health Statistics",courseUG4Meta:"48 hours · Required",courseG1:"Mathematical Foundations in Biostatistics",courseG1Meta:"18 hours",teachingAwardsLabel:"Teaching Awards & Textbooks",teachBook1:"Deputy editor, Big Data Epidemiology",teachBook2:"Deputy editor, Statistics",teachAward1:"Second Prize, Shandong University Young Teacher Competition",teachAward2:"Second Prize, School of Public Health Young Teacher Competition",serviceTitle:"Academic Service",serviceA:"Academic & Social Service",service1:"Board Member, Causal Inference Branch, Chinese Association for Applied Statistics",service2:"Committee Member, Shandong Preventive Medicine Association — Digestive Disease and Health Branch",service3:"Young Editorial Board Member, EngMedicine",patentTitle:"Patent & Translation",patentA:"Patent & Translation",patent1:"1 granted invention patent",patent2:"Disease prediction and early-warning system based on uncertainty reasoning in causal networks",patent3:"Technology transfer completed",patentStatus:"GRANTED · TRANSLATED",
 footerQuote:"Build methods that survive heterogeneity.",
 pubTitle:"Publications & Research Outputs",pubLead:"Journal papers also show CAS partition and the highest JIF observed over the latest five-year window.",metricNote:"Metric convention: CAS partition uses publicly available 2025 upgraded-edition information. “5Y Max IF” is the highest publicly reported JIF during 2021–2025, rounded to one decimal. Preprints and non-JCR venues are marked N/A. Journal metrics change annually; please re-check before formal reporting.",
 searchLabel:"Search",searchPlaceholder:"Title / author / journal",filterAll:"All",filterArticles:"Journal articles",filterPreprints:"Preprints",allYears:"All years",resultsLabel:"outputs",noResults:"No matching records.",articleLabel:"Journal article",preprintLabel:"Preprint",casLabel:"CAS",ifLabel:"5Y MAX IF"
}};
let lang=localStorage.getItem("leiHouLang")||(navigator.language||"").toLowerCase().startsWith("zh")?"zh":"en";
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const highlightAuthors=arr=>arr.map(a=>a==="Lei Hou"?`<mark class="author-self">Lei Hou</mark>`:esc(a)).join(", ");
function applyLanguage(l){lang=l;localStorage.setItem("leiHouLang",l);document.documentElement.lang=l==="zh"?"zh-CN":"en";document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(T[l][k]!=null)el.textContent=T[l][k]});document.querySelectorAll("[data-i18n-placeholder]").forEach(el=>{const k=el.dataset.i18nPlaceholder;if(T[l][k]!=null)el.placeholder=T[l][k]});document.querySelectorAll(".lang-btn").forEach(b=>b.classList.toggle("active",b.dataset.lang===l));renderPublications()}
document.querySelectorAll(".lang-btn").forEach(b=>b.onclick=()=>applyLanguage(b.dataset.lang));
const header=document.querySelector(".site-header");addEventListener("scroll",()=>header?.classList.toggle("scrolled",scrollY>20),{passive:true});
const mt=document.querySelector(".menu-toggle"),mp=document.querySelector(".mobile-panel");if(mt&&mp){mt.onclick=()=>mp.classList.toggle("open");mp.querySelectorAll("a").forEach(a=>a.onclick=()=>mp.classList.remove("open"))}
const obs="IntersectionObserver"in window?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");obs.unobserve(e.target)}}),{threshold:.06}):null;document.querySelectorAll(".reveal").forEach(el=>obs?obs.observe(el):el.classList.add("visible"));
let typ="all",yr="all",q="";const list=document.getElementById("publication-list"),count=document.getElementById("pub-count"),empty=document.getElementById("pub-empty"),search=document.getElementById("pub-search"),yf=document.getElementById("year-filter");
function renderPublications(){if(!list||!window.PUBLICATIONS)return;const t=T[lang];const rows=window.PUBLICATIONS.filter(p=>(typ==="all"||p.type===typ)&&(yr==="all"||String(p.year)===yr)&&(`${p.title} ${p.venue} ${(p.authors||[]).join(" ")} ${p.year}`).toLowerCase().includes(q.toLowerCase()));list.innerHTML=rows.map(p=>`<article class="pub-item"><div class="pub-date">${esc(p.year)}<br>${esc(p.month)}</div><div class="pub-main"><h3>${p.url?`<a href="${esc(p.url)}" target="_blank" rel="noreferrer">${esc(p.title)} ↗</a>`:esc(p.title)}</h3><p class="pub-authors">${highlightAuthors(p.authors||[])}</p><div class="pub-meta-line"><span class="pub-badge venue">${esc(p.venue)}</span><span class="pub-badge type">${p.type==="article"?t.articleLabel:t.preprintLabel}</span>${p.note?`<span class="pub-badge">${esc(p.note)}</span>`:""}</div>${p.doi?`<div class="pub-doi">DOI: ${esc(p.doi)}</div>`:""}</div><aside class="pub-metrics"><div><small>${t.casLabel}</small><b>${esc(p.cas)}</b></div><div><small>${t.ifLabel}</small><b>${esc(p.peakIF)}</b></div></aside></article>`).join("");if(count)count.textContent=rows.length;if(empty)empty.hidden=rows.length>0}
if(window.PUBLICATIONS&&yf){[...new Set(window.PUBLICATIONS.map(p=>p.year))].sort((a,b)=>b-a).forEach(y=>{const o=document.createElement("option");o.value=y;o.textContent=y;yf.appendChild(o)});yf.onchange=e=>{yr=e.target.value;renderPublications()};document.querySelectorAll(".filter-chip").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter-chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");typ=b.dataset.type;renderPublications()});search?.addEventListener("input",e=>{q=e.target.value.trim();renderPublications()})}
applyLanguage(lang);
})();
